function Story() {
    return (
        <div>
            <h3 className="homeText">Story</h3>
            <br></br>
            <p className="homeText">
	       Paris, France, 1904. Leaving the police station morgue, Linda Brasseur was ready to enjoy and evening of tranquility. It was Friday, and she wouldn't be needed in until Tuesday if she was lucky. The station was well on its' way to finding the culprit behind the death of Patrick Hawks, some American tourist. While she walked home through the streets of Paris, Mr. Hawks dead corpse remained in the morgue, until it would depart tomorrow morning for cremation on behalf of the Hawks family's wishes.

	       A group of teenage kids were roaming late, passing by the station. One of the kids had provoked the other into a challenge. John-Phillipe was one of the teenaged boys, whose father was the police chief. Another in the group, Bastien, had dared the group to perform a magic ritual he found in his father's desk drawer. This ritual is written to summon a demon. Of course, it is all in Latin, and most of the writing held no meaning to the group of boys. Perhaps peer pressure, or fear of being called a coward had pushed John-Phillipe to say yes, as he opened the stations doors with his father's key. Nobody was really there at midnight, it would be simple to sneak into a private room.

	       The boys best bet would be the morgue, as it would be locked and presumed empty by this time of night, while some other parts of the station could be required in an emergency. The boys chatted about who brought the chalk, the candles and other ritualistic items they could make out in the spell. Laying out a pentagram, with candles at the points of the star, the setup was complete. Bastien spoke first, the other boys, including John-Phillipe, joining in shortly. Nothing happened, they spoke the words, but everything was the same. Seconds later, the candles blew out, but none of the boys could have done it. Quickly, they locked eyes, adrenaline starting to course through their bodies, with the realization sinking in. With dark purple skin, with a fleshy tail, and glowing eyes, stood their demon. The exchange felt simple enough, after the demon had asked what the boys wanted, the group relaxed. Isaac, a third boy in the group, piped up first, asking for his parents to be brought back from the dead. The demon wasn't tricky like a genie, but it also didn't truly have the power of resurrection. Luckily, it had collected a curious vial of blue liquid. The demon explained this vial was acquired from another dimension, which had served to revive fallen... alien species. While the demon was unwilling to make any promises, it stated that this vial was all it could offer.

	       The boys hesitated, but Isaac seemed excited and unworried. While Bastien started to stop him, Isaac reached out and took the vial, the demon smiled, congratulating Isaac, and it told him that he would give him a better deal. Usually a demon collects a soul, after a certain amount of time, taking matters into their own hands, but the demon told Isaac he would let him live as long as life permitted, and take his soul afterwards.

	       The demon had told him how it works, merely a few drops should bring a person back, at least that is how it worked when the demon saw it in effect. John-Phillipe and Bastien told Isaac to try it on one of the bodies in the morgue, they weren't convinced of its' effect. Isaac obliged, though unnerved, to use some of the blue fluid, tapping the side, with the vial tilted, to get a couple drops into the corpse's mouth. The boys happened to pull out the man Patrick Hawks, whom was killed much earlier that day. For a while, nothing was happening, a couple minutes had passed, and the demon was gone. Isaac was growing dissapointed, hoping the vial would have worked. As the boys prepared to give up, they suddenly saw the body twitch. The eyes opened, dull blue, the corpse's arms and legs started to twitch and move more dramatically. Bastien screamed, and John-Phillipe stood frozen. Isaac just kept backing up. Bumping into the wall, Isaac jumped, accidentally dropping the vial. It shattered on the floor, and blue smoke rose up from the liquid. The boys ran, and the body remained twitching about, violently.

	       When Linda woke up the next morning, she thought about what she would do that weekend. Free time, all to herself. A knock landed upon her door, and she answered. Chief Lagarde, from the station, stood at the door, a worried look in his eyes.  

            
            </p>
        </div>
    );
}
export default Story